### ISSUE TITLE
Add GitHub style formatting

### ISSUE THREAD

**Issue by Keith94** [KeithLRobertson/markdown-viewer#1]
Hi and thanks for the cool add-on! :)

Would it be possible to change the markdown formatting to look exactly like GitHub? For example, make the document centered with a border surrounding it; also have borders under the headers and have the same font, colors etc.

![image](https://user-images.githubusercontent.com/5490615/27132195-bac12940-50c2-11e7-8f92-1ac9515c969c.png)

**Comment by KeithLRobertson** [comment]
Thanks for the feedback. I hope you like it!

Yes, in a future version, I intend to let the user set the style in which Markdown documents are viewed, so keep a lookout for changes! :-)  (This is very much a side "time available" project, so I can't say how soon that will happen.)

**Comment by Keith94** [comment]
Yes, it's nice to finally have a markdown viewer that works in Firefox 57+.

Do you plan on adding pre-configured themes (GitHub etc.), or the ability to customize it entirely?

**Comment by KeithLRobertson** [comment]
Both!

**Comment by Fromax** [comment]
@Keith94 :  In the meanwhile, you can download a copy of GitHub CSS, save it as `_markdown.css` in the same directory as your markdown files, and voilà ! See #14 .

**Comment by KeithLRobertson** [comment]
Note. _markdown.css is no longer relevant. Instead go to the add-on's options page and paste the CSS content there.

**Comment by Cimbali** [comment]
Also shipped in the menu in [v1.5.0](https://github.com/KeithLRobertson/markdown-viewer/releases/tag/1.5.0).
