### ISSUE TITLE
Show subtitles i.e. titles levels >=3

### ISSUE THREAD

**Issue by tukoz** [KeithLRobertson/markdown-viewer#10]
Subtitles aren't rendered under *Firefox Nightly* 58.0 with *Markdown Viewer Webext* 1.2.0

![subtitles not displayed](https://i.gyazo.com/0870aa9fe907ed97b3890f496c29eca7.png)

Please am I missing something?

**Comment by jledruide** [comment]
It seems to be OK for me.

![capture du 2017-10-09 13-08-35](https://user-images.githubusercontent.com/4048263/31335476-0eeb9af0-acf3-11e7-9120-b4127da16d5a.png)

    Firefox Nightly 57.0b6 (64 bits) Firefox Developer Edition
    Linux Mint Cinnamon
    Markdown Viewer Webext 1.2.0

**Comment by KeithLRobertson** [comment]
@tukoz Are you sure there aren't hidden characters in your document around the triple-hashes? That would cause the markdown/html converter to not style it. If you can provide the original raw .md document, the community and I can figure out why it's not styling.

**Comment by KeithLRobertson** [comment]
No response, so can't diagnose.
