### ISSUE TITLE
option to set/edit document for new tabs (firefox)

### ISSUE THREAD

**Issue by atomGit** [KeithLRobertson/markdown-viewer#109]
i'm liking this extension - very smartly done and had no trouble on linux after creating .mime.types

would it be possible to add an option to load a document for all new tab pages as well as the ability to edit it (i know i'm asking a lot here)?

i'm currently using [Mark-It](https://github.com/mattang687/mark-it) for that (no longer on AMO) and being able to view/edit an MD doc on new tabs is an amazingly handy way to keep some bookmarks, code, notes, etc.

**Comment by Cimbali** [comment]
Hi @atomGit, thanks for suggestions. Editing is a bit out of scope unfortunately. For new tab pages you can put any page I think, including markdown pages. Maybe you’d need an add-on such as [new tab override](https://addons.mozilla.org/en-GB/firefox/addon/new-tab-override/)
