### ISSUE TITLE
question on text encoding

### ISSUE THREAD

**Issue by shijialee** [KeithLRobertson/markdown-viewer#11]
Hi, 

Great plugin, very easy to use!

I am running latest firefox nightly.

One question for text encoding.. To view markdown in chinese, I had to manually change the encoding every time I open/reload the md file. The default in firefox in this case is always western.

I am not sure the right solution(set encoding in this plugin?) or if this should be solved by markdown-viewer. 

Any thoughts?

**Comment by KeithLRobertson** [comment]
Your markdown file needs to start with a Byte Order Marker (BOM). This will tell Firefox what encoding it's in.

**Comment by Croydon** [comment]
@shijialee Can't you just change the default encoding in Firefox to UTF-8 somehow?
