### ISSUE TITLE
Heading anchors

### ISSUE THREAD

**Issue by lmnoop** [KeithLRobertson/markdown-viewer#12]
Would it be possible to do what VS Code does with headings? Consider this md:
```
* [Overview](#overview)
	* [Terminology](#terminology)
		* [Resource](#resource)
		* [Collection](#collection)
		* [Controller](#controller)
* [General](#general)
	* [Who is the API for?](#who-is-the-api-for)
* [Designing URIs](#designing-uris)

# Overview
## Terminology
### Resource
### Collection
### Controller
# General
## Who is the API for?
# Designing URIs
```

It produces a TOC where the clickable sections scroll the document to the appropriate heading. Since I can't inspect the output HTML in VS Code, I don't know whether they are doing
`<h1 id="overview">Overview</h1>`
or
`<h1><a name="overview"></a>Overview</h1>`
or what but the result is pretty nice.

**Comment by glennmurray** [comment]
This would be a great feature.  Note that Emacs's markdown-toc package creates the same table of contents, but with the asterisks replaced by hyphens.

**Comment by KeithLRobertson** [comment]
Even better if the TOC were auto-generated from the headings in the document. There may be a plugin for markdown-it which could be integrated into the add-on. (Would be great if somehow user-configurable, whether it activates and to what header depth.) It's not my expertise, though; another contributor integrated the plugin for checkboxes.

**Comment by KeithLRobertson** [comment]
Thanks @Cimbali for implementing this feature!
