### ISSUE TITLE
Not opening .md files - Linux

### ISSUE THREAD

**Issue by sigmasoldi3r** [KeithLRobertson/markdown-viewer#16]
OS: `ElementaryOS 0.4.1 Loki x64 (Built on Ubuntu 16.04.3 LTS)`
Firefox version: `59.0a1 (2017-11-20) (64-bit) Nightly (Quantum)`

### The problem

When attempting to open markdown files from the disk, the browser just asks to save them.

#### Source

The plugin is installed from [addons.mozilla](https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-webext/)

**Comment by Myu-Unix** [comment]
Hi,

There's a workaround here https://github.com/KeithLRobertson/markdown-viewer/issues/2 but indeed a fix would be nicer

**Comment by sigmasoldi3r** [comment]
Working! I'll leave it open for users who look for the same workaround.

Thanks!!

**Comment by Fromax** [comment]
The workaround at #2 (_create mime type_) also fixes things in **OpenIndiana** Hipster (Solaris).
- Firefox 52.5.0 ESR
- MATE desktop 1.18

**Comment by KeithLRobertson** [comment]
Thanks, @Myu-Unix for linking the workaround. It would be nice if the add-on could address that but I don't think it can. (Anyone is welcome to try; the project is open source and completely free.) The choice to download or view is made by Firefox long before activating the add-on. So any fix would have to be in Firefox itself.

**Comment by ildar** [comment]
What's the FF devs reasoning of this misbehavior? Anyone asked?
