### ISSUE TITLE
Disabling Javascript disables this viewer

### ISSUE THREAD

**Issue by Metadope** [KeithLRobertson/markdown-viewer#18]
Thanks for this extension. I've only tested it (thus far) with my experimental [Basilisk](https:\\www.basilisk-browser.org) install.

I was surprised to discover that it stops working when I disable javascript (as opposed to Thiht's extension, which continues to work even after JS browsing is disabled (via [about:config](about:config))).

Maybe this is how all WebExtensions work?

Most of my browsing is done with JS disabled, and I often view MD files from local storage, so it would be nice if markdown-viewer worked under these circumstances.

**Comment by KeithLRobertson** [comment]
Yes, WebExtensions are thoroughly based on JavaScript. I imagine that any extension which tries to modify a page by injecting JavaScript would be unable to work with JS disabled.
