### ISSUE TITLE
Please start using GitHub release (and therefore git tags)

### ISSUE THREAD

**Issue by Croydon** [KeithLRobertson/markdown-viewer#19]
Please start using GitHub release (and therefore git tags) this really helps to notice new versions much easier without getting notifications for every single thing going on in this project.

If you want to keep track of a lot of projects it's simply way too much spam, being able to just keeping tracks of new releases is really the resuce.

Thanks for your work here :)

**Comment by KeithLRobertson** [comment]
I think I've got this started, as requested. Thanks for the suggestion!
