### ISSUE TITLE
Document shown as plain text

### ISSUE THREAD

**Issue by sebastienadam** [KeithLRobertson/markdown-viewer#22]
For some time, when I open a document, it's shown as plain text (not formatted).

I'm using FF 58.0.1 on Windows 10.

Any idea of the problem?

Thanks.

**Comment by KeithLRobertson** [comment]
Is this with local (file:) or remote (http:) URLs? If remote, then this is issue #8. Something changed in Firefox permissions. "Since 56.0, tabs.executeScript() doesn't work for non-local documents."

If local, then it's new; please describe in detail.

**Comment by sebastienadam** [comment]
I've solved the problem by uninstalling FF, removing profile and reinstalling FF.

Maybe there were something corrupted in the profile :-/

**Comment by sebastienadam** [comment]
The problem was encountered with local files.

**Comment by KeithLRobertson** [comment]
Thanks for letting us know and closing! :-)
