### ISSUE TITLE
Default encoding (suggestion)

### ISSUE THREAD

**Issue by sebastienadam** [KeithLRobertson/markdown-viewer#26]
Since UTF-8 is ASCII compatible, why not using UTF-8 as the default encoding? Not all editors support UTF-8 BOM.

Best have: an option to set the default encoding? 👍

**Comment by KeithLRobertson** [comment]
I agree! I would welcome a submission to this open source project that fixes it. I haven't figured out how to specify the encoding as UTF-8 if the document doesn't have a BOM.

**Comment by sebastienadam** [comment]
I'll be happy to help you, but I don't have experience with nodejs and web-ext :'(

**Comment by KeithLRobertson** [comment]
@sebastienadam, I don't either really, but they're very easy to set up for just rebuilding the extension.
