### ISSUE TITLE
Firefox screenshot tool doesn't work when markdown file is open in tab

### ISSUE THREAD

**Issue by j86989** [KeithLRobertson/markdown-viewer#27]
When markdown file is open in tab, Firefox screenshot tool options are gray and inactive.

**Comment by KeithLRobertson** [comment]
Hmm. It works perfectly for me, FF 59.0.1 64-bit on Windows. What's your environment?

**Comment by Cimbali** [comment]
Works fine with FF60.0 64-bit in openSUSE too.

**Comment by KeithLRobertson** [comment]
Request for more information received no response. Closing.

**Comment by j86989** [comment]
I have just tried to take a screenshot of markdown file and it works now.
