### ISSUE TITLE
The viewer is not triggered on raw.githubusercontent.com

### ISSUE THREAD

**Issue by georgthegreat** [KeithLRobertson/markdown-viewer#33]
E. g.  https://raw.githubusercontent.com/KeithLRobertson/markdown-viewer/master/README.md

Even when this domain is enabled in addon settings, I see raw markdown instead of compiled one.

Is there any reason for such behavior?

**Comment by KeithLRobertson** [comment]
Yes. Those pages include CSP headers, so FF refuses to allow extensions to inject scripts. I guess it's a security feature.

I didn't know this either until @Cimbali pointed this out in issue #25.
