### ISSUE TITLE
Export as HTML

### ISSUE THREAD

**Issue by y6nH** [KeithLRobertson/markdown-viewer#35]
If you use Firefox's Save option, the page is saved as Markdown. That's fine, but it would be really useful to have an export option too, for sharing HTML files with people who don't have a MD viewer. Ideally, it would inline the CSS and some smaller images (as base-64 data urls).

**Comment by KeithLRobertson** [comment]
Good idea. PRs welcome if you'd like to contribute the feature. In the meantime you can do this:
- Open your markdown.
- F12 for developer tools.
- Select the `<html>` root element in the Inspector tab.
- Right-click -> Edit as HTML.
- Ctrl-A to select all.
- Ctrl-C to copy.
- Paste into your favorite text editor and save.

**Comment by Cimbali** [comment]
Shipped in [v1.5.0](https://github.com/KeithLRobertson/markdown-viewer/releases/tag/1.5.0).
