### ISSUE TITLE
Feature - Dark Mode or Custom CSS

### ISSUE THREAD

**Issue by jakemayfield** [KeithLRobertson/markdown-viewer#36]
Hi @KeithLRobertson ,

I just left a [5-star review](https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-webext/reviews/) for this plugin in the Firefox Add-ons marketplace. I also mentioned that I'd love to see a toggled "dark/night" view mode that could invert the black on white. Or, *possibly*, even a custom CSS box in the Settings where the users could add custom formatting for viewing the markdown.

Are you open to any such feature(s)?

Are you open to reviewing any pull requests if I were to consider writing such a feature?

Thanks!

**Comment by jakemayfield** [comment]
Just realized the custom CSS is already in the works! DOH! Thanks! Closed.

**Comment by KeithLRobertson** [comment]
Was going to point that out. :-) Many thanks to @Cimbali for contributing that feature!
And yes, PRs are welcome.
