### ISSUE TITLE
Frecnh language support

### ISSUE THREAD

**Issue by geraldvannier** [KeithLRobertson/markdown-viewer#37]
Hi,
not sure if it can be solved easily..
In french, we have chars like "é" , "ê", "ô" etc..
Here is what I see now in the browser:  rÃ©pondre  (instead of répondre).

**Comment by lesurp** [comment]
It's a firefox issue, not related (directly) to the extension.

A quick fix is setting `intl.charset.fallback.utf8_for_file` to true (see https://superuser.com/questions/1215064/change-firefox-default-encoding-for-text-files), basically telling firefox open all local files as utf-8 encoded.

Another solution is to specify the BOM in the file, which is quite annoying, to say the least.

**Comment by geraldvannier** [comment]
Correct! Thanks :) it fixes the issue.

**Comment by KeithLRobertson** [comment]
Thank you, @pLesur ! I didn't know about that option. Very helpful!
