### ISSUE TITLE
No formatting on Firefox 60 on Windows

### ISSUE THREAD

**Issue by kwbBaker** [KeithLRobertson/markdown-viewer#39]
Installed add-on, restarted Firefox, opened *.md file, and it still shows up as plain text, no formatting.  This is firefox quantum version 60.0.2 64-bit.

**Comment by KeithLRobertson** [comment]
With the markdown file open as you describe, click on the Markdown icon on the toolbar, upper right by the menu. This gives the extension permission to intercept markdown files. You only need to do this once per site (where local file system counts as a site). Or, go to the Add-Ons Extensions page for the Markdown plugin, and *then* click the toolbar icon; this will grant permissions for all sites.  (However, be aware that some sites like raw.githubusercontent.com emit CORS headers which prevent the plugin from rewriting the page.)

**Comment by kwbBaker** [comment]
Yep.  Thanks.  This wasn't mentioned in the description anywhere so I 
never noticed it.
-- 

Keith W. Blackwell
Software Design Engineer
Machine Health*
Tel:  +1 (970) 282-6065
Fax: +1 (970) 282-1010
keith.blackwell@skf.com
* Innovation & Business Development / Rotating Equipment Performance 
Development

SKF USA Inc.
4812 McMurry Avenue, Fort Collins, CO 80525
www.skf.com, Facebook, LinkedIn, Twitter, Instagram, YouTube
SKF – The Power of Knowledge Engineering

This communication constitutes an electronic communication within the 
meaning of the Electronic Communication Privacy Act 18 U.S.C. 2510 et. 
Seq., and any unauthorized interception of this communication is strictly 
prohibited by law. If the reader of this message is not the intended 
recipient, you are hereby notified that any dissemination, distribution or 
copying of this communication is strictly prohibited. If you have received 
this communication in error, please notify the sender immediately by reply 
e-mail and delete the message and any attachments.
