### ISSUE TITLE
anchor link is not working with non english characters

### ISSUE THREAD

**Issue by Abu-Abdullah** [KeithLRobertson/markdown-viewer#49]
Hi,

it seems anchor link is not working with non english characters. can you try this:

```
1. [متطلبات التشغيل الأولي](#متطلبات-التشغيل-الأولي)
2. [اكتشاف الكاميرات](#اكتشاف-الكاميرات)

# متطلبات التشغيل الأولي
* تجربة

# اكتشاف الكاميرات
* تجربة
```

**Comment by Cimbali** [comment]
Seems to be a side-effect of the regex we use, from https://gist.github.com/asabaylus/3071099#gistcomment-1622315

Apparently `\w` only matches ascii alphanumeric characters, not utf-8 characters, so we strip them out.
I don't know how we handle accents in anchors either, like éàñ and so on.
