### ISSUE TITLE
Checkboxes not formatted

### ISSUE THREAD

**Issue by RaffaeleMorganti** [KeithLRobertson/markdown-viewer#5]
great addon, there is only a problem: it doesn't format checkboxes/tasklists
```
* [ ] Check
```
displayed:
* [] Check

expected:
* [ ] Check

**Comment by KeithLRobertson** [comment]
That's a feature of the underlying [markdown-it](https://github.com/markdown-it/markdown-it) library. Post an issue there, and if they change it let me know, and I can update this extension with their new version.

**Comment by RaffaeleMorganti** [comment]
I looked into it and found that this library has some plugins: https://www.npmjs.com/browse/keyword/markdown-it-plugin.

So they will not add into markdown-it this functionality since this is available in [markdown-it-checkbox](https://www.npmjs.com/package/markdown-it-checkbox) plugin.

I hope in future you can implement this.
Regards.

**Comment by KeithLRobertson** [comment]
I'll keep it in mind. Thanks. Also, this is open source; I'd certainly be willing to accept a PR for it.

**Comment by KeithLRobertson** [comment]
I apologize for the long delay. I tried to get to this each weekend and something kept coming up. I have an additional feature to add, and then I'll push this to Mozilla as 1.2.
