### ISSUE TITLE
Table of contents does not scroll

### ISSUE THREAD

**Issue by gaul** [KeithLRobertson/markdown-viewer#53]
My TOC viewport fits about 9.5 elements and does not scroll.  Could you add scrollbars or honor the mouse wheel for this element?

**Comment by Cimbali** [comment]
You mean when it has a fixed position I suppose ? Otherwise it scrolls with the page (so that's a quick work-around for now).

I'll look into making the TOC scrollable.

**Comment by Cimbali** [comment]
You mean when it has a fixed position I suppose ? Otherwise it scrolls with the page (so that's a quick work-around for now).

I'll look into making the TOC scrollable.

**Comment by gaul** [comment]
I want the TOC itself to scroll so I can see more than 9.5 elements.  The fixed position is fine.

**Comment by Cimbali** [comment]
Atually in both cases we cut off & hide the TOC if too long. Working on a fix.

**Comment by Cimbali** [comment]
Can you give that PR a try @gaul ? Seems to have fixed it for me.
