### ISSUE TITLE
Optional plugins

### ISSUE THREAD

**Issue by Cimbali** [KeithLRobertson/markdown-viewer#55]
I found myself adding a bunch of plugins and re-building the extension for my own personal use (markdown footnotes, fancy lists). I did not contribute those as I felt they probably would not be of much interest, or at least not to too many people, and they would probably bloat or be undesired by some people as well.

Is it a better idea to include those and make them optional, via an option on the preferences page for example ?

**Comment by KeithLRobertson** [comment]
Yeah it's a fine balance between what's widely useful and bloat. Not too worried about the size of the plugin download.

I am concerned about having large JS files parsed into the page that aren't used. So if we can make them optional based on settings, and also conditional -- as in dynamically loaded like we were doing previously -- I would be all for making it feature-rich.


On May 6, 2019 5:35:38 AM EDT, Cimbali <notifications@github.com> wrote:
>I found myself adding a bunch of plugins and re-building the extension
>for my own personal use (markdown footnotes, fancy lists). I did not
>contribute those as I felt they probably would not be of much interest,
>or at least not to too many people, and they would probably bloat or be
>undesired by some people as well.
>
>Is it a better idea to include those and make them optional, via an
>option on the preferences page for example ?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/KeithLRobertson/markdown-viewer/issues/55

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cimbali** [comment]
That's a good point! Dynamic loading will probably delay the parsing of the markdown a little (probably negligibly? I don't know) for each enabled plugin.

**Comment by KeithLRobertson** [comment]
Yeah, if the features are loaded by the manifest like the main scripts, they would consume computation to parse them for every .md page load, even if the feature is disabled. Even if markdown transformation is turned off! Plus there's the memory they would consume while the page is open. Perhaps it's not that much for any one page, but multiply that by ever page loaded by every user. It just feels so wasteful.

And we've already done it. So it's a bit of coding to put that back in, but we don't have to research how to do dynamic loading. There wasn't any noticeable delay.

Downside is I think it won't work for file:// URLs :-(, unless Mozilla has fixed that issue. As I recall, that was why we took out the dynamic loading.


On May 16, 2019 12:50:35 PM EDT, Cimbali <notifications@github.com> wrote:
>That's a good point! Dynamic loading will probably delay the parsing of
>the markdown a little (probably negligibly? I don't know) for each
>enabled plugin.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/KeithLRobertson/markdown-viewer/issues/55#issuecomment-493146637

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
