### ISSUE TITLE
Vim-vixen incompatibility

### ISSUE THREAD

**Issue by paulfariello** [KeithLRobertson/markdown-viewer#57]
Markdown-viewer doesn't render the page when it's installed alongside vim-vixen.
How can I have more logs about Markdown-viewer?

**Comment by Cimbali** [comment]
Does vim-vixen modify the html of the page? You can check the source code of the page to verify that.

If so, this might be the same type of conflict as #41: we detect that the page needs to be rendered by the fact that it contains a single `pre` tag.

**Comment by paulfariello** [comment]
Yes it does. So this is a duplicated issue.
Thanks.
