### ISSUE TITLE
distorted icon

### ISSUE THREAD

**Issue by gaul** [KeithLRobertson/markdown-viewer#61]
The icon in `about:addons` is elongated, perhaps because it is not square:

![image](https://user-images.githubusercontent.com/848247/62965270-82a59580-bdb9-11e9-9565-23585ba3c99e.png)

**Comment by Cimbali** [comment]
I can’t seem to fix this, neither by playing with the svg nor by exporting to png. I suppose something in Firefox is blindly cropping the surrounding empty space.

**Comment by Cimbali** [comment]
This is actually already fixed but didn’t appear so to me because the icon was cached.
