### ISSUE TITLE
Getting no styles renderization when selecting "github" code style

### ISSUE THREAD

**Issue by mfandrade** [KeithLRobertson/markdown-viewer#65]
When I go to the menu and select "github" markdown code style my markdown renders like a plain HTML with no styles.

Trying to debug this, I could see that javascript console shows the message below.

>The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

Then I have saved my markdown file with BOM but couldn't get this working yet.

Digging at the web, I found [this StackOverflow question](https://stackoverflow.com/q/24604466), although I was not able to fix this issue.

I'm on a Debian Buster, with Firefox 68.2.0esr and no other add-ons installed at all.

Regards.

**Comment by Cimbali** [comment]
I’m sorry, can you specify what you expect and what you actually get? The GitHub style adds a horizontal line under `<h2>` tags and makes rows in tables alternate in colours. 

If you download and open [this test file](https://github.com/KeithLRobertson/markdown-viewer/raw/master/test/test-file.md) in your browser, is that what you see?

There is a [variant test file without BOM](https://github.com/KeithLRobertson/markdown-viewer/raw/master/test/test-nobom.md) which will show the warning you’re talking about, but I don’t think that’s relevant − it will only affect encoding detection in some specific cases.
