### ISSUE TITLE
Typo on Readme under Linix support for local files

### ISSUE THREAD

**Issue by frrobert2** [KeithLRobertson/markdown-viewer#76]
On the README file under Linux Support for local files the second option is:

```
2. Another workaround (which might cover other OSs as well), is to edit Firefox’s private mime types.

These mime types are stored in a file indicated by helpers.private_mime_types_file, by default it is ~/.mime.types. Create this file if it does not exist, otherwise edit it, and add the following line:

type=text/plain exts=md,mkd,mkdn,mdwn,mdown,markdown desc="Markdown document"

Then restart Firefox.
```
The line that says type=    should be
`
type=text/plain exts=md,mkd,mkdn,mdwn,mdown,markdown, desc="Markdown document"`

The last file ext should have a comma after it otherwise Firefox will not recognize it as a valid extension.

**Comment by Cimbali** [comment]
Are you sure about this ? On my machine it seems to work fine without the trailing comma. Or is it a Firefox version thing ? Running v85 here.
Is there a reference for this file somewhere maybe?

**Comment by frrobert2** [comment]
I am running 85.0.1 on Ubuntu 20.04. I just verified it again.  If I don't have a trailing comma after the last extension the last extension is not recognized.  The ones with commas are.  If I add a comma after the last extension then all the extensions are recognized including the last one.   

I just figured this out by trial and error.  I wonder if it is a difference in OSs.

**Comment by Cimbali** [comment]
Hmm you’re right actually ! I didn’t realize it only affected the last extension of the list.
