### ISSUE TITLE
Cannot clone Git repository recursively

### ISSUE THREAD

**Issue by kgraefe** [KeithLRobertson/markdown-viewer#78]
The submodule `highlightjs` points to a non-existant commit ID. Reading your commit message https://github.com/KeithLRobertson/markdown-viewer/commit/76ba76cdcf0b572f509cb1a8091fdd6f6b58bc16 you probably missed to update `.gitmodules` (https://github.com/highlightjs/cdn-release.git happens to have that commit)

**Comment by Cimbali** [comment]
Thanks for reportingi ! The `.gitmodules` was indeed not updated
