### ISSUE TITLE
The non-breacking space is parsed as a normal whitespace

### ISSUE THREAD

**Issue by ThePirate42** [KeithLRobertson/markdown-viewer#80]
While searching for a way to force multiple subsequent newlines in markdown without using html, I found this trick: if you start a line with a non-breacking space, that line is still considered to be containing actual text, wich means that, for example, a sequence of `newline-nonbreackingspace-newline-newline` will generate an "invisible" paragraph, and won't just be collapsed. This trick sadly doesn't seem to work everywere, your extension included, but at least it works in Github:

---

test

 

 

 

test

---

 Since this works in Github, shouldn't this be at least supported in Github mode?

**Comment by Cimbali** [comment]
We don’t do the markdown rendering, but defer to `markdownit`. Instead of using a non-breakable space, you could use a tolerated HTML tag, such as `<br />`:

```md
a

<br />

b
```
Which renders with a skipped paragraph both with `markdownit` and with github:

> a
> 
> <br />
> 
> b

vs. without `<br />` line:

> a
> 
> b

**Comment by Cimbali** [comment]
By the way the “github” option is purely stylistic. It’s not a “mode”, it just affects the way the markdown rendering looks.
