### ISSUE TITLE
Does not activate on web files (Firefox, Windows)

### ISSUE THREAD

**Issue by jacktose** [KeithLRobertson/markdown-viewer#82]
Is this extension supposed to work on markdown files hosted on the web? I assume so, because there's nothing to the contrary in the readme or existing issues.

When I load a `.md` file from a `file://` URL, it renders nicely. When I open it from an `http[s]://` URL ([example][README.md]), it displays as plain text, with no extension menu. Here's an example from a fresh install in Windows Sandbox:
![md-remote]

Windows 10 19043.1165, Firefox 91.0.1

[README.md]: https://raw.githubusercontent.com/KeithLRobertson/markdown-viewer/master/README.md
[md-remote]: https://user-images.githubusercontent.com/12414794/129947950-73c36859-8542-41ec-9f21-70c672afaa3c.png

**Comment by Cimbali** [comment]
That’s ony on githubusercontent I think, where the content-security-policy explicitely forbids it. See the headers:

```
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
```

See for example [this raw markdown file from a gitlab repo](https://gitlab.com/gnachman/iterm2/-/raw/master/README.md). Other markdown files in the wild should work too − and those on github already have a rendered version.

**Comment by Cimbali** [comment]
It’s actually said (briefly) in the README, with that specific example:

> To keep it simple, the extension does not support on and off states. If the document has one of the supported extensions, it should convert. Some web sites however, like raw.githubusercontent.com, return CORS headers, in which case Firefox will not inject this extension's content scripts, so it cannot convert the document.

**Comment by jacktose** [comment]
Oops, bad luck with choice of test specimen, and a big RTFM to me. Thanks.
