### ISSUE TITLE
Add support for TABLE markdown syntax

### ISSUE THREAD

**Issue by SirWumpus** [KeithLRobertson/markdown-viewer#83]
```
|Header1 |Header2  | Header3|
--- | --- | ---
|data1|data2|data3|
|data11|data12|data13|
```

See https://www.w3schools.io/file/markdown-table/

GitHub, Phabricator, GitLab (I think) and others support this syntax.  Wouldbe nice to have.

Thanks.

**Comment by Cimbali** [comment]
These already work. You’re missing a leading and closing `|` on the second tow of your syntax:

```
|Header1|Header2|Header3|
|--- | --- | ---|
|data1|data2|data3|
|data11|data12|data13|
```

It’s part of the test file, here’s how that renders:

![image](https://user-images.githubusercontent.com/6126377/130334282-51816f9e-fda6-4a41-959f-8ccfea117d7d.png)


The test file also shows the different alignment options:
```
| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| col 1 is      | some wordy text | $1600 |
| col 2 is      | centered        |   $12 |
| zebra stripes | are neat        |    $1 |
```

**Comment by SirWumpus** [comment]
![Screenshot 2021-08-21 at 16-49-23 CMDR Snert](https://user-images.githubusercontent.com/7441729/130334464-d40b2996-1022-4fc8-ac9f-9b8e91f4d12c.png)
In my actual use case I was doing
```
Rankings
--------

|Combat     | Almost Elite       |
|Trader     | Elite              |
|Exploration| Elite              |
|CQC        | What's That?       |
|BPit       | Born To The Onesie |
```
There are trailing `  ` (space-space after the closing `|`)  I had no heading.  It wasn't formatted by the plugin.  Often I want a table structure without headings.

**Comment by SirWumpus** [comment]
The table only works if I add an empty header row and  divider line...
```
Rankings
--------

 |             |                    |  
 |:------------|:-------------------|  
 | Combat      | Almost Elite       |  
 | Trader      | Elite              |  
 | Exploration | Elite              |  
 | CQC         | What's That?       |  
 | BPit        | Born To The Onesie |  
```

**Comment by Cimbali** [comment]
Yes markdown tables always require headers, that’s just how the specs are. It’s also the case on github and everywhere else. The following code:

```
| a | b |
| c | d |
```

Renders as:

| a | b |
| c | d |
