### ISSUE TITLE
Download as HTML only includes plaintext stylesheet

### ISSUE THREAD

**Issue by Melandel** [KeithLRobertson/markdown-viewer#85]
Hello,

Using:
* Windows 10
* Firefox 92.0.1
* the latest version of markdown-viewer on firefox addons website
* `github`/`github-gist theme`

When I click on `Download as HTML`, the output renders without css.

I have a workaround, which is to copy the outer HTML from the html tag, but it would be much more practical if the `Download as HTML` button works correctly.

**Comment by Cimbali** [comment]
Thanks @Melandel ! I’ve uploaded the fixed version, we’ll see how much time it takes to make it through the AMO review.
