### ISSUE TITLE
Add-on icon for dark mode Firefox

### ISSUE THREAD

**Issue by ratijas** [KeithLRobertson/markdown-viewer#91]
Same issue as https://github.com/piroor/treestyletab/issues/3040 (resolved).

Please, provide an adaptive icon for this Markdown Viewer add-on, so it can be visible on dark background.

![Screenshot_20220115_224718](https://user-images.githubusercontent.com/6737986/149635758-ac05a221-05c2-45de-8331-f3cfe27d68c9.png)

**Comment by Cimbali** [comment]
With a 75% opaque white background we could look like this:

![image](https://user-images.githubusercontent.com/6126377/149666945-61b8a0b6-9d0a-4075-b9a1-a4ceb3bb3df4.png)

That is, unchanged on white background, readable but not too aggressively white on dark backgrounds.
